# Generated by Django 4.1 on 2022-12-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passengenr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passengenr',
            new_name='Passenger',
        ),
    ]
